#!/usr/bin/env python3
"""
Generate a new agent from template.
Creates boilerplate code for SDK agents, ADK agents, or multi-agent systems.
"""

import argparse
import os
from pathlib import Path


TEMPLATES = {
    "sdk": {
        "description": "Basic Vertex AI SDK agent",
        "filename": "agent.py",
        "content": '''"""
Simple agent using Vertex AI SDK.
Generated by agent-demo/scripts/generate_agent.py
"""

from google import genai
from google.api_core import exceptions


class {class_name}:
    """A simple agent using Vertex AI SDK."""

    def __init__(self, project_id: str, location: str = "us-central1"):
        """Initialize the agent."""
        self.client = genai.Client(vertexai=True, location=location)
        self.model = "gemini-2.5-flash"
        self.system_instruction = """{instruction}"""

    def chat(self, message: str) -> str:
        """Send a message and get a response."""
        try:
            response = self.client.models.generate_content(
                model=self.model,
                contents=message,
                config={{
                    "system_instruction": self.system_instruction
                }}
            )
            return response.text

        except exceptions.ResourceExhausted as e:
            return f"Error: API quota exceeded. {{e}}"

        except exceptions.InvalidArgument as e:
            return f"Error: Invalid request - {{e}}"

        except Exception as e:
            return f"Error: {{e}}"


if __name__ == "__main__":
    import sys

    # Get project ID from environment
    project_id = os.environ.get("PROJECT_ID")
    if not project_id:
        print("Error: Set PROJECT_ID environment variable")
        sys.exit(1)

    # Create agent
    agent = {class_name}(project_id=project_id)

    # Interactive loop
    print("Agent ready. Type 'quit' to exit.")
    while True:
        try:
            user_input = input("\\nYou: ").strip()
            if user_input.lower() in ["quit", "exit"]:
                break

            response = agent.chat(user_input)
            print(f"Agent: {{response}}")

        except KeyboardInterrupt:
            print("\\nExiting...")
            break
'''
    },

    "adk": {
        "description": "ADK agent with tools",
        "filename": "agent.py",
        "content": '''"""
ADK agent with tools.
Generated by agent-demo/scripts/generate_agent.py
"""

from google.adk.agents import LlmAgent
from google.adk.tools import google_search, code_execution


def create_agent() -> LlmAgent:
    """Create and configure the agent."""
    agent = LlmAgent(
        name="{agent_name}",
        model="gemini-2.5-flash",
        instruction="""{instruction}""",
        description="{description}",
        tools=[google_search, code_execution]
    )
    return agent


if __name__ == "__main__":
    # Create agent
    agent = create_agent()

    # Interactive loop
    print("Agent ready. Type 'quit' to exit.")
    while True:
        try:
            user_input = input("\\nYou: ").strip()
            if user_input.lower() in ["quit", "exit"]:
                break

            response = agent.run(input=user_input)
            print(f"\\nAgent: {{response.text}}")

        except KeyboardInterrupt:
            print("\\nExiting...")
            break
'''
    },

    "multi-agent": {
        "description": "Multi-agent system with coordinator",
        "filename": "multi_agent_system.py",
        "content": '''"""
Multi-agent system with coordinator.
Generated by agent-demo/scripts/generate_agent.py
"""

from google.adk.agents import LlmAgent


def create_specialist_agent(name: str, domain: str) -> LlmAgent:
    """Create a specialist agent for a specific domain."""
    return LlmAgent(
        name=name,
        model="gemini-2.5-flash",
        instruction=f"You are an expert in {{domain}}. Provide accurate, detailed information.",
        description=f"Specialist agent for {{domain}}"
    )


def create_coordinator() -> LlmAgent:
    """Create the coordinator agent."""
    # Create specialist agents
    specialist_1 = create_specialist_agent("specialist_1", "research")
    specialist_2 = create_specialist_agent("specialist_2", "analysis")

    # Create coordinator with sub-agents
    coordinator = LlmAgent(
        name="coordinator",
        model="gemini-2.5-flash",
        instruction="""{instruction}""",
        description="Coordinates between specialist agents",
        tools=[specialist_1, specialist_2]
    )

    return coordinator


if __name__ == "__main__":
    # Create multi-agent system
    coordinator = create_coordinator()

    # Interactive loop
    print("Multi-agent system ready. Type 'quit' to exit.")
    while True:
        try:
            user_input = input("\\nYou: ").strip()
            if user_input.lower() in ["quit", "exit"]:
                break

            response = coordinator.run(input=user_input)
            print(f"\\nCoordinator: {{response.text}}")

        except KeyboardInterrupt:
            print("\\nExiting...")
            break
'''
    }
}


def generate_agent(template_type: str, output_dir: Path, **kwargs):
    """Generate agent from template."""
    if template_type not in TEMPLATES:
        print(f"Error: Unknown template type '{template_type}'")
        print(f"Available: {', '.join(TEMPLATES.keys())}")
        return False

    template = TEMPLATES[template_type]

    # Create output directory
    output_dir.mkdir(parents=True, exist_ok=True)

    # Format template content
    content = template["content"].format(**kwargs)

    # Write file
    output_file = output_dir / template["filename"]
    output_file.write_text(content)

    print(f"✓ Generated {template['description']}")
    print(f"  File: {output_file}")
    print(f"\nNext steps:")
    print(f"  1. Review and customize the generated code")
    print(f"  2. Set PROJECT_ID environment variable")
    print(f"  3. Run: python {output_file}")

    return True


def main():
    parser = argparse.ArgumentParser(
        description="Generate agent boilerplate from templates"
    )
    parser.add_argument(
        "template",
        choices=list(TEMPLATES.keys()),
        help="Template type"
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("."),
        help="Output directory (default: current directory)"
    )
    parser.add_argument(
        "--name",
        default="MyAgent",
        help="Agent name (default: MyAgent)"
    )
    parser.add_argument(
        "--instruction",
        default="You are a helpful assistant.",
        help="System instruction"
    )
    parser.add_argument(
        "--description",
        default="A helpful AI agent",
        help="Agent description"
    )

    args = parser.parse_args()

    # Generate class name from agent name
    class_name = args.name.replace(" ", "").replace("-", "").replace("_", "")
    agent_name = args.name.lower().replace(" ", "_")

    generate_agent(
        args.template,
        args.output,
        class_name=class_name,
        agent_name=agent_name,
        instruction=args.instruction,
        description=args.description
    )


if __name__ == "__main__":
    main()
